api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

messenger:
    resource: "@MessengerBundle/Controller/"
    type:     annotation